config/routes.rb
Rails.application.routes.draw do

resources :items, :image_url

root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_type
  validates :title, presence: true
  def completed?
	completed_on != nil
  end
end

app/models/item_type.rb
class ItemType < ActiveRecord::Base
	has_many :items
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
	  #@image_url = ImageFetcher.new.fetch(@item.title)
      redirect_to items_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(item_params)
	  #@image_url = ImageFetcher.new.fetch(@item.title)
      redirect_to items_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:title, :completed_on, :item_type_id, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <% if @item.errors.any? %>
    <div class='errors'>
      <h2>Uh oh, errors!</h2>
      <% @item.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :item_type, 'What type of item is this?' %>
    <%= f.collection_select :item_type_id, ItemType.all, :id, :name %>
  </div>

  <div class='field'>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class='field'>
    <%= f.label :image_url %>
    <%= f.text_field :image_url%>
  </div>
  
  <div class='field'>
    <%= f.label :completed_on %>
    <%= f.date_select :completed_on, :include_blank => true%>
  </div>

  <div class='field'>
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<h1>List of Items </h1>

<p><%= link_to 'New item', new_item_path %></p>

<% img_fetcher = ImageFetcher.new %>
<% @items.each do |item| %>
<p>
<%= item.title %><br>
<%=item.item_type.name%><br>
<%if item.image_url != nil%>
<img src="<%=img_fetcher.fetch(item.image_url)%>" alt="Image here" width="300" height="300"><br>
<%end%>
<% if item.completed? %>
Complete
<% else %>
Incomplete
<% end %><br>
<p>
<%= link_to 'Edit', edit_item_path(item) %>
<%= link_to 'Delete', item_path(item), method: :delete %>
</p>
</p>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ItemsLibrary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>